model:
  name: logistic_regression
  solver: saga
  penalty: l2
  C: 1.0
  max_iter: 2000
  n_jobs: -1
  random_state: 42
  cv_folds: 5

preprocessing:
  normalize: true
  normalize_with_mean: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation type
      - Location
      - Isolation source
      - Testing standard

  pca:
    enabled: true
    n_components: 50
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 0.001

  select_variance_k:
    enabled: true
    k: 10000
    
  select_xgboost_k:
    enabled: false
    k: 20000

  select_k_best:
    enabled: true
    k: 100000

  select_first_k:
    enabled: false
    k: 10000

  lda:
    enabled: false
    mode: "shrinkage"   # "classic", "regularized", "shrinkage", "kernel"
    n_components: 10
    shrinkage_value: null
    kernel: "rbf"       # "rbf", "poly", "linear", "sigmoid"
    gamma: 
    degree: 3
    coef0: 1.0