model:
  name: logistic_regression
  solver: saga
  penalty: l2
  C: 1.0
  max_iter: 2000
  n_jobs: -1
  random_state: 42

preprocessing:
  normalize: true
  normalize_with_mean: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation source
      - Testing standard
      - Isolation type
      - Location

  pca:
    enabled: true
    n_components: 50
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 0.001

  select_first_k:
    enabled: true
    k: 10000