model:
  name: linear_svm
  C: 1.0
  loss: hinge
  max_iter: 5000
  random_state: 42

preprocessing:
  normalize: true
  normalize_with_mean: false

  pca:
    enabled: true
    n_components: 100
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 0.0005

  select_first_k:
    enabled: false
    k: 250000