model:
  name: xgboost
  booster: gbtree
  eta: 0.10638951516952143
  max_depth: 7
  min_child_weight: 9
  subsample: 0.7675651067098845
  colsample_bytree: 0.5870314251531698
  reg_lambda: 30.56949278920439
  reg_alpha: 4.635035012131066
  n_estimators: 964
  tree_method: auto
  max_bin: 250
  n_jobs: -1
  random_state: 42
  eval_metric: logloss
  cv_folds: 5
preprocessing:
  normalize: false
  one_hot_encode:
    enabled: true
    columns:
    - Isolation type
    - Location
    - Isolation source
    - Testing standard
  pca:
    enabled: true
    n_components: 200
    svd_solver: randomized
  variance_threshold:
    enabled: true
    threshold: 1
  select_variance_k:
    enabled: false
    k: 8000
  select_xgboost_k:
    enabled: false
    k: 200
  select_k_best:
    enabled: false
    k: 20000
  select_first_k:
    enabled: false
    k: 200000
hyperoptimization:
  type: optuna
  random:
    n_iter: 40
    n_estimators: None
  grid:
    n_estimators:
    - 500
    - 1000
    - 1500
  optuna:
    n_trials: 150
    eta:
      type: float
      low: 0.01
      high: 0.15
      log: true
    max_depth:
      type: int
      low: 4
      high: 10
    min_child_weight:
      type: int
      low: 3
      high: 9
    subsample:
      type: float
      low: 0.5
      high: 0.9
    colsample_bytree:
      type: float
      low: 0.4
      high: 0.85
    reg_lambda:
      type: float
      low: 5.0
      high: 200.0
      log: true
    reg_alpha:
      type: float
      low: 1.0
      high: 100.0
      log: true
    n_estimators:
      type: int
      low: 300
      high: 1200
    booster: None
    tree_method: None
    max_bin: None
    eval_metric: None
