model:
  name: stack
  random_state: 42
  cv_folds: 5

  lr:
    name: logistic_regression
    solver: saga
    penalty: elasticnet
    C: 0.5
    l1_ratio: 0.5
    max_iter: 10000
    n_jobs: -1
    random_state: 42
    cv_folds: 5

  svm:
    name: svm
    C: 0.5
    kernel: rbf
    gamma: scale
    shrinking: true     
    probability: true    
    tol: 0.0001
    max_iter: 10000
    class_weight: balanced
    decision_function_shape: ovr
    break_ties: false
    random_state: 42
    cv_folds: 5
  
  randomized_tree:
    name: randomized_tree
    cv_folds: 5
    n_jobs: -1

    n_estimators: 800

    min_samples_split: 10
    min_samples_leaf: 5
    max_samples: 0.7
    bootstrap: True


    max_features: sqrt
    max_depth: 12

    criterion: entropy

    class_weight: balanced

    random_state: 42

  xgboost:
    booster: gbtree
    eta: 0.07
    max_depth: 5
    min_child_weight: 7
    subsample: 0.86
    colsample_bytree: 0.80
    reg_lambda: 5.72
    reg_alpha: 1.01
    n_estimators: 900
    tree_method: hist
    max_bin: 250
    n_jobs: -1
    random_state: 42
    eval_metric: logloss
    cv_folds: 5

  random_forest:
    name: random_forest
    n_estimators: 900
    min_samples_split: 10
    min_samples_leaf: 2
    max_features: sqrt
    max_depth: 15
    bootstrap: true
    criterion: entropy
    class_weight: balanced_subsample
    random_state: 42
    n_jobs: -1
    cv_folds: 5

preprocessing:
  normalize: true
  normalize_with_mean: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation type
      - Location
      - Isolation source
      - Testing standard

  pca:
    enabled: false
    n_components: 50
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 1

  select_k_best:
    enabled: true
    k: 400       # <- your chosen 400 best features

  select_variance_k:
    enabled: false
    k: 10000

  select_xgboost_k:
    enabled: false
    k: 20000

  select_first_k:
    enabled: false
    k: 10000

  lda:
    enabled: false
    mode: "shrinkage"
    n_components: 10
    shrinkage_value: null
    kernel: "rbf"
    gamma:
    degree: 3
    coef0: 1.0
