model:
  name: xgboost
  booster: gbtree

  eta: 0.05
  max_depth: 6
  min_child_weight: 5

  subsample: 0.75
  colsample_bytree: 0.5

  lambda: 5.0
  alpha: 1.0

  n_estimators: 500
  tree_method: hist
  max_bin: 250
  n_jobs: -1

  random_state: 42
  eval_metric: logloss
  cv_folds: 5

preprocessing:
  normalize: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation type
      - Location
      - Isolation source
      - Testing standard

  pca:
    enabled: false
    n_components: 300
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 0.0003

  select_variance_k:
    enabled: true
    k: 10000
    
  select_xgboost_k:
    enabled: true
    k: 20000

  select_k_best:
    enabled: false
    k: 20000

  select_first_k:
    enabled: false
    k: 200000
