model:
  name: xgboost
  booster: gbtree
  eta: 0.1
  max_depth: 8
  subsample: 0.8
  colsample_bytree: 0.8
  n_estimators: 300
  tree_method: hist
  n_jobs: -1
  random_state: 42
  eval_metric: logloss
  cv_folds: 5

preprocessing:
  normalize: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation source
      - Testing standard
      - Isolation type
      - Location

  pca:
    enabled: false
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 0.0003

  select_first_k:
    enabled: true
    k: 200000
