model:
  name: xgboost
  booster: gbtree

  eta: 0.05
  max_depth: 4
  min_child_weight: 10

  subsample: 0.7
  colsample_bytree: 0.4

  lambda: 5.0
  alpha: 2.0

  n_estimators: 300
  tree_method: hist
  max_bin: 250
  n_jobs: -1

  random_state: 42
  eval_metric: logloss
  cv_folds: 5

preprocessing:
  normalize: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation type
      - Location
      - Isolation source
      - Testing standard

  pca:
    enabled: true
    n_components: 300
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 0.0003

  select_k_best:
    enabled: true
    k: 15000

  select_first_k:
    enabled: false
    k: 200000
