model:
  name: random_forest
  cv_folds: 5
  n_jobs: -1
  n_estimators: 1145
  min_samples_split: 4
  min_samples_leaf: 1
  max_features: sqrt
  max_depth: 10
  criterion: entropy
  bootstrap: true
  class_weight: balanced_subsample
  random_state: 42
preprocessing:
  normalize: true
  one_hot_encode:
    enabled: true
    columns:
    - Isolation type
    - Location
    - Isolation source
    - Testing standard
  pca:
    enabled: false
    svd_solver: randomized
  variance_threshold:
    enabled: true
    threshold: 1
  select_variance_k:
    enabled: false
    k: 10000
  select_xgboost_k:
    enabled: false
    k: 8000
  select_k_best:
    enabled: true
    k: 200
  select_first_k:
    enabled: false
    k: 150000
  lda:
    enabled: false
    mode: shrinkage
    n_components: 10
    shrinkage_value: null
    kernel: null
    gamma: null
    degree: 3
    coef0: 1.0
hyperoptimization:
  type: optuna
  optuna:
    n_trials: 150
    max_depth:
      type: int
      low: 5
      high: 14
    n_estimators:
      type: int
      low: 300
      high: 1400
    min_samples_split:
      type: int
      low: 2
      high: 20
    min_samples_leaf:
      type: int
      low: 1
      high: 10
    max_features:
      type: categorical
      values:
      - sqrt
      - log2
    class_weight:
      type: categorical
      values:
      - null
      - balanced
