model:
  name: stack
  random_state: 42
  cv_folds: 5

  lr:
    name: logistic_regression
    solver: saga
    penalty: elasticnet
    C: 1.0
    l1_ratio: 0.5
    max_iter: 5000
    n_jobs: -1
    random_state: 42
    cv_folds: 5

  svm:
    name: svm
    C: 0.5
    kernel: rbf
    gamma: scale
    shrinking: false
    probability: true
    tol: 0.001
    max_iter: 5000
    class_weight: balanced
    decision_function_shape: ovr
    break_ties: false
    random_state: 42
    cv_folds: 5

  rf:
    n_estimators: 1081
    min_samples_split: 20
    min_samples_leaf: 1
    max_features: sqrt
    max_depth: 18
    criterion: entropy
    bootstrap: false
    class_weight: balanced_subsample
    random_state: 42
    n_jobs: -1


preprocessing:
  normalize: true
  normalize_with_mean: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation type
      - Location
      - Isolation source
      - Testing standard

  pca:
    enabled: false
    n_components: 50
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 1

  select_variance_k:
    enabled: false
    k: 10000
    
  select_xgboost_k:
    enabled: false
    k: 20000

  select_k_best:
    enabled: true
    k: 200

  select_first_k:
    enabled: false
    k: 10000

  lda:
    enabled: false
    mode: "shrinkage"   # "classic", "regularized", "shrinkage", "kernel"
    n_components: 10
    shrinkage_value: null
    kernel: "rbf"       # "rbf", "poly", "linear", "sigmoid"
    gamma: 
    degree: 3
    coef0: 1.0