model:
  name: xgboost
  booster: gbtree

  eta: 0.05
  max_depth: 6
  min_child_weight: 5

  subsample: 0.75
  colsample_bytree: 0.50

  reg_lambda: 10.0
  reg_alpha: 2.0

  n_estimators: 500
  tree_method: auto
  max_bin: 250
  n_jobs: -1

  random_state: 42
  eval_metric: logloss
  cv_folds: 5

preprocessing:
  normalize: true
  normalize_with_mean: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation type
      - Location
      - Isolation source
      - Testing standard

  pca:
    enabled: false
    n_components: 1000
    svd_solver: full

  variance_threshold:
    enabled: true
    threshold: 1

  select_variance_k:
    enabled: false
    k: 8000
    
  select_xgboost_k:
    enabled: true
    k: 500

  select_k_best:
    enabled: false
    k: 500

  select_first_k:
    enabled: false
    k: 200000

  lda:
    enabled: false      
    mode: shrinkage         # classic | shrinkage | kernel
    n_components: null 
    shrinkage_value: auto 
    kernel: rbf          # rbf | poly | linear; only used if mode: kernel
    gamma: null      


hyperoptimization:

  type: optuna

  random:
    n_iter: 40
    n_estimators: None

  grid:
    n_estimators: [500, 1000, 1500]

  optuna:
    n_trials: 150

    eta:
      type: float
      low: 0.01
      high: 0.15
      log: true

    max_depth:
      type: int
      low: 4
      high: 10

    min_child_weight:
      type: int
      low: 3
      high: 9

    subsample:
      type: float
      low: 0.50
      high: 0.90

    colsample_bytree:
      type: float
      low: 0.40
      high: 0.85

    reg_lambda:
      type: float
      low: 5.0
      high: 200.0
      log: true

    reg_alpha:
      type: float
      low: 1.0
      high: 100.0
      log: true

    n_estimators:
      type: int
      low: 300
      high: 1200

    booster: None
    tree_method: None
    max_bin: None
    eval_metric: None
