model:
  name: logistic_regression
  solver: newton-cg
  penalty: l2
  C: 1.0
  max_iter: 2000
  n_jobs: -1
  random_state: 42
  cv_folds: 5

preprocessing:
  normalize: true
  normalize_with_mean: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation type
      - Location
      - Isolation source
      - Testing standard

  pca:
    enabled: false
    n_components: 50
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 1

  select_variance_k:
    enabled: false
    k: 10000
    
  select_xgboost_k:
    enabled: false
    k: 20000

  select_k_best:
    enabled: true
    k: 200

  select_first_k:
    enabled: false
    k: 10000

  lda:
    enabled: false
    mode: "shrinkage"   # "classic", "regularized", "shrinkage", "kernel"
    n_components: 10
    shrinkage_value: null
    kernel: "rbf"       # "rbf", "poly", "linear", "sigmoid"
    gamma: 
    degree: 3
    coef0: 1.0
    
hyperoptimization:
  type: optuna
  optuna: 
    n_trials: 150

    C:
    type: float
    low: 1e-4
    high: 10.0
    log: true

  penalty:
    type: categorical
    values: ["l2", "elasticnet"]

  solver:
    type: categorical
    values: ["liblinear", "saga"]

  l1_ratio:
    type: float
    low: 0.0
    high: 1.0
    # Only used when penalty = "elasticnet"

  class_weight:
    type: categorical
    values: [null, "balanced"]

  tol:
    type: float
    low: 1e-6
    high: 1e-2
    log: true

  max_iter:
    type: int
    low: 200
    high: 1500