model:
  name: randomized_tree
  cv_folds: 5
  n_jobs: -1
  n_estimators: 1082
  min_samples_split: 9
  min_samples_leaf: 4
  max_samples: 0.8736778581132036
  bootstrap: true
  max_features: sqrt
  max_depth: 17
  criterion: entropy
  class_weight: balanced
  random_state: 42
preprocessing:
  normalize: false
  one_hot_encode:
    enabled: true
    columns:
    - Isolation type
    - Location
    - Isolation source
    - Testing standard
  pca:
    enabled: false
    svd_solver: randomized
  variance_threshold:
    enabled: true
    threshold: 0.1
  select_variance_k:
    enabled: false
    k: 10000
  select_xgboost_k:
    enabled: false
    k: 8000
  select_k_best:
    enabled: false
    k: 200
  select_first_k:
    enabled: false
    k: 150000
  lda:
    enabled: false
    mode: shrinkage
    n_components: 10
    shrinkage_value: null
    kernel: null
    gamma: null
    degree: 3
    coef0: 1.0
hyperoptimization:
  type: optuna
  optuna:
    n_trials: 150
    n_estimators:
      type: int
      low: 200
      high: 1200
      log: false
    max_depth:
      type: int
      low: 6
      high: 18
    min_samples_split:
      type: int
      low: 2
      high: 20
    min_samples_leaf:
      type: int
      low: 2
      high: 15
    max_samples:
      type: float
      low: 0.4
      high: 0.9
