model:
  name: linear_svm
  cv_folds: 5
  random_state: 42

  penalty: l2
  tol: 0.0001
  loss: squared_hinge
  C: 0.5
  dual: true
  max_iter: 10000
  fit_intercept: true
  intercept_scaling: 1.0
  class_weight: balanced


preprocessing:
  normalize: true
  normalize_with_mean: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation type
      - Location
      - Isolation source
      - Testing standard

  pca:
    enabled: false
    n_components: 100
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 1

  select_variance_k:
      enabled: false
      k: 500
  
  select_xgboost_k:
    enabled: false
    k: 20000

  select_k_best:
    enabled: true
    k: 500

  select_first_k:
    enabled: false
    k: 250000
