model:
  name: xgboost
  booster: gbtree

  eta: 0.03
  max_depth: 10
  min_child_weight: 5

  subsample: 0.85
  colsample_bytree: 0.6

  lambda: 2.0
  alpha: 0.5

  n_estimators: 900
  tree_method: hist
  max_bin: 250
  n_jobs: -1

  random_state: 42
  eval_metric: logloss
  cv_folds: 5

preprocessing:
  normalize: false

  one_hot_encode:
    enabled: true
    columns:
      - Isolation type
      - Location
      - Isolation source
      - Laboratory typing platform
      - Testing standard

  pca:
    enabled: false
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 0.0003

  select_first_k:
    enabled: true
    k: 200000
