model:
  name: logistic_regression
  solver: saga
  penalty: elasticnet
  C: 6.575436425895147
  max_iter: 10000
  n_jobs: -1
  random_state: 42
  cv_folds: 5
  l1_ratio: 0.5897641716335503
  tol: 0.0017969352382172115
preprocessing:
  normalize: true
  normalize_with_mean: false
  one_hot_encode:
    enabled: true
    columns:
    - Isolation type
    - Location
    - Isolation source
    - Testing standard
  pca:
    enabled: false
    n_components: 50
    svd_solver: randomized
  variance_threshold:
    enabled: true
    threshold: 1
  select_variance_k:
    enabled: false
    k: 10000
  select_xgboost_k:
    enabled: false
    k: 20000
  select_k_best:
    enabled: true
    k: 200
  select_first_k:
    enabled: false
    k: 10000
  lda:
    enabled: false
    mode: shrinkage
    n_components: 10
    shrinkage_value: null
    kernel: rbf
    gamma: null
    degree: 3
    coef0: 1.0
hyperoptimization:
  type: optuna
  optuna:
    n_trials: 100
    C:
      type: float
      low: 0.0001
      high: 10.0
      log: true
    l1_ratio:
      type: float
      low: 0.0
      high: 1.0
    tol:
      type: float
      low: 1.0e-06
      high: 0.01
      log: true
