model:
  name: xgboost
  booster: gbtree
  eta: 0.1
  max_depth: 8
  subsample: 0.8
  colsample_bytree: 0.8
  n_estimators: 300
  tree_method: hist
  n_jobs: -1
  random_state: 42

preprocessing:
  normalize: false

  pca:
    enabled: false
    svd_solver: randomized

  variance_threshold:
    enabled: true
    threshold: 0.0003

  select_first_k:
    enabled: true
    k: 200000
